### ISSUE TITLE
GMUTE-error

### ISSUE THREAD

**Issue by kinoko2k** [kinokoBOT-project/kinoko-globalchat2.js#10]
`  const gmute = (gmutes.get(message.author.id)) || { score: 0, reason: 0 }`
でエラーが発生

`
/home/kinoko/kinoko/global.js:85
  const gmute = (await gmute.get(message.author.id)) || { score: 0, reason: 0 }
                                     ^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
`
解決者求む
(await gmute.getでエラーが出てる)

**Comment by racoondevelopper** [comment]
すでにgmuteを定義している？

**Comment by kinoko2k** [comment]
定義してないはず

**Comment by kinoko2k** [comment]
定義はconstだよね？

**Comment by kinoko2k** [comment]
```
const Keyv = require("keyv")
const gmutes = new Keyv("sqlite://gmutes.sqlite", {table: "gmutes"});
```
で、Keyvを入れたら
```
    const gmute = (await gmutes.get(message.author.id)) || { score: 0, reason: 0 }
    if(gmute.score != 0) return;
```
await gmutesのgmutesでエラーが出た。

**Comment by kinoko2k** [comment]
webhookのやーつはhttps://qiita.com/chasyumens/items/2500abc01ad2cb888a95
から取り出してるお

**Comment by kinoko2k** [comment]
embedにするか
